create table if not exists public.listings (
  id bigint generated by default as identity (start with 1000) primary key,
  created_at timestamptz not null default now(),
  title text not null,
  area text not null,
  address text not null,
  price integer not null default 0,
  deposit integer not null default 0,
  agency integer not null default 0,
  utilities integer not null default 0,
  rooms integer not null default 1,
  lifestyle text not null default 'New listing',
  safety text not null default 'Pending',
  noise text not null default 'Review',
  match integer not null default 90,
  verified boolean not null default false,
  video boolean not null default false,
  deal text not null default 'Freshly uploaded by landlord',
  image text not null,
  gallery jsonb not null default '[]'::jsonb,
  agent text not null,
  phone text not null,
  rating numeric not null default 4.6,
  response text not null default 'new',
  distance text not null default 'Add nearby schools, shops, and transport',
  views integer not null default 0,
  status text not null default 'available' check (status in ('available', 'booked', 'occupied'))
);

alter table public.listings enable row level security;

drop policy if exists "Anyone can view listings" on public.listings;
create policy "Anyone can view listings"
on public.listings
for select
using (true);

drop policy if exists "Anyone can add listings" on public.listings;
create policy "Anyone can add listings"
on public.listings
for insert
with check (true);

drop policy if exists "Anyone can update listing status" on public.listings;
create policy "Anyone can update listing status"
on public.listings
for update
using (true)
with check (true);
